# Start with our docker development environment image
image:
  name: covergenius/xpay-workspace
  # Run as laradock user
  run-as-user: 1000

pipelines:
  default:
    - step:
        name: Build Assets
        caches:
          - composer
        script:
          - composer install 2>&1
          - composer dump -o 2>&1
        artifacts:
          - vendor/**

    - step:
        name: Run Tests
        script:
          - cp -f ./.env.pipelines .env
          - composer test 2>&1
