name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    steps:
      - uses: actions/checkout@master

      - name: setup php
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, xdebug, soap
          coverage: xdebug

      - name: install deps
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: run tests
        run: cp -f .env.pipelines .env && composer test
