name: Composer

on: [push, pull_request]

jobs:
  static-analysis:
    name: Composer Scans

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@master

      - name: setup php
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          extensions: json, xdebug
          coverage: xdebug

      - name: validate composer.json
        run: composer validate

      - name: install deps
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: composer audit
        run: composer audit
